package temaClaseAbstracta;

public class ClaseAbstractaJavaApuntes {
	
	//EN LAS CLASES ABSTRACTAS NO SE INSTANCIAS OBJETOS
	//SOLO DEFINIRA METODOS Y ATRIBUTOS COMUNES
	//SI UN METODO ES ABSTRACT, LA CLASE DEBE SER ABSTRACT
	//SI LA CLASEO ES ABSTRACTA, NO TIENEN PORQUE TENER NINGUN METODO O ELEMENTOS ABSTRACTOS
	//UN METODO ABSTRACTA NO PUEDE SER ESTATICO
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
